spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/PiyushKumarPU/config-repo.git
          default-label: main
          search-paths: smart-ecommerce

server:
  port: 8888

